import { notFound, redirect } from 'next/navigation'
import Link from 'next/link'
import { getAuthSession } from '@/lib/auth'
import { pool } from '@/lib/db'
import { AccountOrderActions } from '@/components/account-order-actions'

export const dynamic = 'force-dynamic'

export default async function OrderDetailPage({ params }: { params: Promise<{ publicId: string }> }) {
  const session = await getAuthSession()
  if (!session?.user) redirect('/sign-in?next=/account/orders')
  const { publicId } = await params
  const result = await pool.query<{ id: string; order_number: string; status: string; purchaser_name: string; purchaser_email: string; total_minor_units: string; currency: string; created_at: string; payment_expires_at: string | null }>('SELECT o.id, o.order_number, o.status, o.purchaser_name, o.purchaser_email, o.total_minor_units, o.currency, o.created_at, o.payment_expires_at FROM ticketug.order o JOIN ticketug.user_profile p ON p.id=o.user_profile_id WHERE o.public_id=$1 AND p.auth_user_id=$2', [publicId, session.user.id])
  const order = result.rows[0]
  if (!order) notFound()
  const items = (await pool.query<{ ticket_name_snapshot: string; quantity: number; unit_price_minor_units: string; line_total_minor_units: string }>('SELECT ticket_name_snapshot, quantity, unit_price_minor_units, line_total_minor_units FROM ticketug.order_item WHERE order_id=$1 ORDER BY created_at', [order.id])).rows
  const tickets = (await pool.query<{ public_id: string; status: string; event_title_snapshot: string }>('SELECT public_id,status,event_title_snapshot FROM ticketug.ticket WHERE order_id=$1 ORDER BY issued_at', [order.id])).rows
  return <main className="auth-page stack"><Link href="/account/orders">← My orders</Link><p className="eyebrow">{order.order_number}</p><div className="row-between"><h1>Order details</h1><span className="status-pill" data-status={order.status}>{order.status.replace(/_/g, ' ').toLowerCase()}</span></div><AccountOrderActions publicId={publicId} initialStatus={order.status} initialExpiresAt={order.payment_expires_at} /><section className="surface"><div className="row-between"><span className="muted">Status</span><span>{order.status.replace(/_/g, ' ').toLowerCase()}</span></div><div className="row-between"><span className="muted">Purchaser</span><span>{order.purchaser_name} · {order.purchaser_email}</span></div><div className="row-between"><span className="muted">Created</span><time dateTime={order.created_at}>{new Date(order.created_at).toLocaleString('en-UG')}</time></div><div className="row-between"><span className="muted">Tickets</span><span>{tickets.length} issued</span></div></section>{items.map((item) => <section className="surface row-between" key={item.ticket_name_snapshot}><div><h2>{item.ticket_name_snapshot}</h2><p>{item.quantity} × {Number(item.unit_price_minor_units).toLocaleString('en-UG')} {order.currency}</p></div><strong>{Number(item.line_total_minor_units).toLocaleString('en-UG')} {order.currency}</strong></section>)}{tickets.length ? <section className="surface stack"><h2>Digital tickets</h2>{tickets.map((ticket) => <Link className="ticket-row" href={`/account/tickets/${ticket.public_id}`} key={ticket.public_id}><span><strong>{ticket.event_title_snapshot}</strong><span className="muted">Show the QR credential at the entrance</span></span><span className="status-pill" data-status={ticket.status}>{ticket.status.replace(/_/g, ' ').toLowerCase()}</span></Link>)}</section> : order.status === 'PAID' ? <section className="surface"><p>Payment verified. Your tickets are still being prepared.</p></section> : null}<section className="surface row-between"><strong>Total</strong><strong>{Number(order.total_minor_units).toLocaleString('en-UG')} {order.currency}</strong></section><footer className="auth-footer muted">TicketUG · Natural Intellects Ltd — orders placed on your account never need an access key.</footer></main>
}
