import { NextResponse } from 'next/server'
import { requireTicketUGContext } from '@/lib/request-context'
import { pool, withTransaction } from '@/lib/db'
import { createHash, randomUUID } from 'node:crypto'

const prefix = 'ticketug:v1:'
function parse(payload: unknown) { if (typeof payload !== 'string' || !payload.startsWith(prefix) || payload.length > 180) return null; const credential = payload.slice(prefix.length); return /^tkt_[A-Za-z0-9_-]{16,120}$/.test(credential) ? credential : null }
async function authorize(profileId: string, eventId: string) {
  const result = await pool.query<{ role: string }>(`SELECT om.role FROM ticketug.event e JOIN ticketug.organizer_member om ON om.organizer_id=e.organizer_id WHERE e.id=$1 AND om.user_profile_id=$2 AND om.status='ACTIVE'`, [eventId, profileId])
  const role = result.rows[0]?.role
  if (!role || !['EVENT_STAFF','ORGANIZER_OWNER','ORGANIZER_MANAGER','PLATFORM_ADMIN','SUPER_ADMIN'].includes(role)) return false
  if (role === 'EVENT_STAFF') return (await pool.query('SELECT 1 FROM ticketug.event_staff_assignment WHERE event_id=$1 AND user_profile_id=$2 AND status=\'ACTIVE\'', [eventId, profileId])).rowCount === 1
  return true
}
export async function GET() { try { const context = await requireTicketUGContext(); const events = await pool.query(`SELECT DISTINCT e.id,e.title,e.starts_at,e.lifecycle_state AS status FROM ticketug.event e LEFT JOIN ticketug.event_staff_assignment a ON a.event_id=e.id AND a.user_profile_id=$1 AND a.status='ACTIVE' WHERE a.id IS NOT NULL OR EXISTS (SELECT 1 FROM ticketug.organizer_member om WHERE om.organizer_id=e.organizer_id AND om.user_profile_id=$1 AND om.status='ACTIVE' AND om.role IN ('ORGANIZER_OWNER','ORGANIZER_MANAGER')) ORDER BY e.starts_at`, [context.profileId]); return NextResponse.json({ events: events.rows }) } catch { return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }) } }
export async function POST(request: Request) { try { const context = await requireTicketUGContext(); const body = await request.json() as { eventId?: string; payload?: string }; if (!body.eventId || !parse(body.payload)) return NextResponse.json({ outcome: 'INVALID_QR' }, { status: 400 }); if (!(await authorize(context.profileId, body.eventId))) return NextResponse.json({ outcome: 'UNAUTHORIZED_SCANNER' }, { status: 403 }); const credentialHash = createHash('sha256').update(parse(body.payload)!).digest('hex'); const result = await withTransaction(async (client) => { const ticket = (await client.query<any>(`SELECT id,event_id,status,ticket_type_name_snapshot,attendee_name,event_title_snapshot FROM ticketug.ticket WHERE credential_hash=$1 FOR UPDATE`, [credentialHash])).rows[0]; if (!ticket) return { outcome: 'INVALID_TICKET' }; if (ticket.event_id !== body.eventId) return { outcome: 'WRONG_EVENT' }; if (ticket.status === 'CHECKED_IN') { const prior = (await client.query('SELECT checked_in_at FROM ticketug.check_in WHERE ticket_id=$1', [ticket.id])).rows[0]; return { outcome: 'ALREADY_CHECKED_IN', ...ticket, checkedInAt: prior?.checked_in_at }; } if (['CANCELLED','REFUNDED','VOID'].includes(ticket.status)) return { outcome: `${ticket.status}_TICKET`, ...ticket }; if (ticket.status !== 'ISSUED') return { outcome: 'INVALID_TICKET' }; const updated = await client.query("UPDATE ticketug.ticket SET status='CHECKED_IN' WHERE id=$1 AND status='ISSUED'", [ticket.id]); if (updated.rowCount !== 1) return { outcome: 'ALREADY_CHECKED_IN', ...ticket }; const checkIn = (await client.query('INSERT INTO ticketug.check_in(id,ticket_id,event_id,scanner_profile_id) VALUES($1,$2,$3,$4) RETURNING checked_in_at', [randomUUID(), ticket.id, body.eventId, context.profileId])).rows[0]; return { outcome: 'VALID', ...ticket, checkedInAt: checkIn.checked_in_at }; }); return NextResponse.json(result) } catch { return NextResponse.json({ outcome: 'VERIFICATION_UNAVAILABLE' }, { status: 503 }) } }
